# STA 141B Data & Web Technologies for Data Analysis

### Lecture 4, 10/10/23, Numpy


### Last week's topics

 - Basics of Python (cont.')
 - Memory Handling in Python
 - Stack and Heap
 - Types
 - Reference Semantics
 - Interning

### Today's topics

 - Modules and Packages
 - NumPy 

### Modules and Packages 

A module is a text file that contains Python code, usually a `.py` file. Any Python file is a module as well, its name being the file's base name without the `.py` extension. A package is a collection of Python modules. 

In R, it is called a script or package. Python's `import` command lets us load code from a module to use in our script or notebook. `import` is like a combination of R's `source` and `library` functions.

Python provides many built-in modules for common tasks (see the [list](https://docs.python.org/3/library/index.html)). Packages provide even more modules.

We can access functions from modules via `.`: 

In [7]:
pi

NameError: name 'pi' is not defined

In [2]:
import math
math.pi

3.141592653589793

You can give imported modules an alias to cut down on typing: 

In [3]:
import math as m
m.pi

3.141592653589793

We can import single functions within a module or package by running

In [4]:
from math import pi
pi

3.141592653589793

Of course, other `math` functions are not imported this way: 

In [5]:
ceil(4.3)

NameError: name 'ceil' is not defined

In [6]:
m.ceil(4.3)

5

Importing only the required functions keep the namespace clean. We can import all functions from one package by running

In [7]:
from math import * # this is called wildcard import

In [8]:
ceil(4.3)

5

Use this with care, in particular if the namespaces of some modules collide! 

The Python style guide allows to import several functions in one line. This is an exception to the one-line-one-statement rule.

In [9]:
from math import pi, ceil

Which of the built-in modules are important?

Module      | Description
----------- | -----------
sys         | info about Python (version, etc)
pdb         | Python debugger
pathlib     | tools for file paths
collections | additional data structures
string      | string processing
re          | regular expressions
datetime    | date processing
urlparse    | tools for URLs
itertools   | tools for iterators
functools   | tools for functions

Python's built-in `math` and `statistics` modules are missing features we need for serious scientific computing, so we use the "SciPy Stack" instead.

The SciPy Stack is a collection of packages for scientific computing (marked with a `*` below). Most scientists working in Python use the SciPy Stack. The 3 most important packages in the stack are:

Package      | Description
------------ | -----------
numpy\*      | arrays, matrices, math/stat functions
scipy\*      | additional math/stat functions
pandas\*     | data frames

There are also several packages available for creating static plots.

Package      | Description
------------ | -----------
matplotlib\* | visualizations
seaborn      | "statistical" visualizations
plotnine     | ggplot2 for Python

Finally, there are many other packages we may use for specific statistical tasks. Some of these are:

Package      | Description
------------ | -----------
requests     | web (HTTP) requests
lxml         | web page parsing (XML & HTML)
beatifulsoup | web page parsing (HTML)
nltk         | natural language processing
spacy        | natural language processing
textblob     | natural language processing
statsmodels  | classical statistical models
scikit-learn | machine learning models
pillow       | image processing
scikit-image | image processing
opencv       | image processing

### NumPy
NumPy is a Python package that provides tools for numerical computing (the name stands for "Numerical Python"). If you use Anaconda, NumPy is already installed.

NumPy is documented [here][link4].

[link4]: https://numpy.org/doc/stable/

In [1]:
import numpy as np # standard naming convention for numpy

NumPy's core feature is the n-dimensional array of <kbd>numpy.ndarray</kbd> object type. NumPy arrays are the basis for almost all of Python's scientific computing packages. They are the Python equivalent of R's built-in vectors.

NumPy arrays use reference semantics, just as <kbd>list</kbd> type objects. 

#### Creating NumPy Arrays

You can create NumPy arrays from lists:

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

A numpy array is a grid of values, all of the same type and is indexed by a tuple of nonnegative integers. A list is the Python equivalent of an array, but is resizeable and can contain elements of different types.

In [4]:
np.array([1, 2.0, 'horse']) # recasts all entries to char

array(['1', '2.0', 'horse'], dtype='<U32')

In [5]:
np.array([1,2.0,3]) # recasts all entries to float

array([1., 2., 3.])

In [6]:
x = np.array([1,2,3]) 
y = np.array([4.1, 5.2, 6.3])
x + y

array([5.1, 7.2, 9.3])

In [7]:
z = [2, 3, 4.0] #list!
x + z # list + array = array

array([3., 5., 7.])

In [8]:
x + 4

array([5, 6, 7])

In [10]:
x + np.array([2, 3, 4, 5])

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

You can create multidimensional arrays, like matrices, from nested lists.

In [11]:
m = np.array([[1, 2, 3], [4, 5, 6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
type(m)

numpy.ndarray

In [13]:
np.shape(m)

(2, 3)

In [14]:
np.size(m)

6

`numpy.matrix` is a subclass of `numpy.ndarray`. It inherits the laters attributes and is restricted to two dimensions. There is no N-dimensional matrix in numpy, only N-dimensional array: see [this](https://numpy.org/doc/stable/reference/arrays.ndarray.html).

In [15]:
m = np.matrix([[1, 2, 3], [4, 5, 6]])
m

matrix([[1, 2, 3],
        [4, 5, 6]])

In [16]:
type(m)

numpy.matrix

In [17]:
np.shape(m)

(2, 3)

NumPy also provides several helper functions to create arrays. See the [documentation](https://numpy.org/doc/stable/user/basics.creation.html) for a full list.

In [18]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [19]:
np.array(range(0, 10, 2))

array([0, 2, 4, 6, 8])

In [20]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Inspecting Arrays

The array attributes `.shape` and `.size` contain information about the structure of the array. A plethora of array methods are also provided. 

In [22]:
x

array([1, 2, 3])

In [23]:
np.size(x)

3

In [24]:
x.shape # returns a tuple! 

(3,)

In [25]:
m.shape

(2, 3)

In [26]:
x.size # like R's length()

3

In [27]:
m.size

6

In [28]:
len(x) # not as neat, but gives same result

3

In [29]:
x.sum()

6

In [32]:
sum(x) # not as neat, but gives same result

6

The array attribute `.dtype` contains the data type of the array's elements.

In [33]:
x.dtype

dtype('int64')

In [34]:
x

array([1, 2, 3])

In [35]:
y

array([4.1, 5.2, 6.3])

In [36]:
y.dtype

dtype('float64')

In [37]:
(x + y).dtype

dtype('float64')

See [here][link5] or [here][link6] for a complete list of Numpy data types.

[link5]: https://docs.scipy.org/doc/numpy-1.15.0/user/basics.types.html
[link6]: https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html#NumPy-Standard-Data-Types 

 The pythonic role of packages is to not only contribute one class (e.g., `ndarray`), but more functions related to the packages role. This is why a variety of additional functions are provided as well.  

In [38]:
np.sin(x)

array([0.84147098, 0.90929743, 0.14112001])

Keep in mind that this is not the same as the `math.sin` function we have imported above. Indeed, this function throws an error:

In [43]:
import math
math.sin(x) # or math.sin(x)

TypeError: only length-1 arrays can be converted to Python scalars

#### Indexing

You can subset NumPy arrays with indexes or Boolean arrays. Again, this is similar to R.

But be careful! Python uses `and` and `or` to combine conditions, but NumPy uses `&` and `|`!

In [44]:
x

array([1, 2, 3])

In [45]:
x[0]

1

In [46]:
x[1]

2

In [47]:
x == x[0:]

array([ True,  True,  True])

In [48]:
m

matrix([[1, 2, 3],
        [4, 5, 6]])

In [49]:
m.shape

(2, 3)

In [61]:
m[1,0]
x = np.array([[1,2,3],[2,3,4]])
x[0,0]

1

In [62]:
x % 2 == 0

array([[False,  True, False],
       [ True, False,  True]])

In [63]:
x[x % 2 == 0] # true or false

array([2, 2, 4])

Note that although only one element is selected, a one-dimensional array is returned! 

In multidimensional arrays, separate indexes for each dimension with commas. The bare slice `:` selects everything in one dimension, just as we have seen in the last lectures. 

In [64]:
m

matrix([[1, 2, 3],
        [4, 5, 6]])

In [65]:
m[:, 0]

matrix([[1],
        [4]])

In [66]:
m[1, :]

matrix([[4, 5, 6]])

In [67]:
m[:, 0:2]

matrix([[1, 2],
        [4, 5]])

In [68]:
m[0,:]

matrix([[1, 2, 3]])

Matrix algebra can performed using `@`. 

In [69]:
m

matrix([[1, 2, 3],
        [4, 5, 6]])

In [72]:
(np.transpose(m) @ m ) #can also use '*' but better practice not to use

matrix([[17, 22, 27],
        [22, 29, 36],
        [27, 36, 45]])

In [100]:
m @ np.transpose(np.matrix([[1, 2, 3]]))

matrix([[14],
        [32]])

So what is NumPy good for?

NumPy also provides functions for:
- Linear algebra (multiplication, transposition, decomposition, ...)
- Random number generation
- Elementary statistics
- Signal processing
- And more...

There isn't time to cover all of these in detail in lecture, but you can learn more from the documentation and references.

## Using NumPy for Monte Carlo Integration
### Example - approximate $\pi$ using Monte Carlo method

Consider a circle with radius 1 circumscribed by a square with side length 2.

The area of the circle is $\pi$, so for a uniform distribution on the square, the probability a point will fall in the circle is $\pi / 4$.

We can estimate the probability to estimate $\pi$.

In [73]:
import numpy as np

def approx_pi(n): 
    # First, we need to sample points (x, y) with x in (0, 1) and y the same
    u = np.random.rand(n, 2) # returns array of dim n # uniform distribution from 0 to 1

    # Check whether sampled point lies in the circle
    in_circle = u[:,0]**2 + u[:,1]**2 <= 1

    # Estimate pi
    pi = 4 * in_circle.mean()
    return pi

In [74]:
approx_pi(1_00_000)

3.14816

In [110]:
np.pi

3.141592653589793

In [111]:
math.pi

3.141592653589793

We have used the package `numpy.random`, a subpackage or NumPy. 

In [ ]:
help(np.random)

There are other packages that produce random numbers, like `random`. 

In [125]:
import random
random.seed(1) # np.random.seed(1) # alternative, but different seed! 

Lets see how how fast our approximation converges. 

In [127]:
log10_nsims = np.linspace(start=0.5, stop=6, num=100)

In [ ]:
nsims = (10**log10_nsims).astype(int)

In [129]:
nsims

array([      3,       3,       4,       4,       5,       5,       6,
             7,       8,      10,      11,      12,      14,      16,
            18,      21,      24,      27,      31,      35,      40,
            46,      52,      59,      68,      77,      87,     100,
           113,     129,     146,     166,     189,     215,     244,
           278,     316,     359,     408,     464,     527,     599,
           681,     774,     879,    1000,    1136,    1291,    1467,
          1668,    1895,    2154,    2448,    2782,    3162,    3593,
          4084,    4641,    5274,    5994,    6812,    7742,    8799,
         10000,   11364,   12915,   14677,   16681,   18957,   21544,
         24484,   27825,   31622,   35938,   40842,   46415,   52749,
         59948,   68129,   77426,   87992,  100000,  113646,  129154,
        146779,  166810,  189573,  215443,  244843,  278255,  316227,
        359381,  408423,  464158,  527499,  599484,  681292,  774263,
        879922, 1000

In [130]:
pi = [approx_pi(n) for n in nsims]
pi

[2.6666666666666665,
 4.0,
 4.0,
 2.0,
 2.4,
 4.0,
 1.3333333333333333,
 2.2857142857142856,
 3.0,
 2.0,
 2.5454545454545454,
 3.6666666666666665,
 2.857142857142857,
 3.25,
 3.3333333333333335,
 3.238095238095238,
 3.3333333333333335,
 2.6666666666666665,
 2.967741935483871,
 2.857142857142857,
 3.4,
 2.9565217391304346,
 3.230769230769231,
 3.1864406779661016,
 3.1176470588235294,
 2.961038961038961,
 3.0804597701149423,
 3.12,
 3.0442477876106193,
 3.2248062015503876,
 3.232876712328767,
 3.1325301204819276,
 3.238095238095238,
 3.0697674418604652,
 3.098360655737705,
 3.079136690647482,
 3.0126582278481013,
 3.1643454038997216,
 3.1470588235294117,
 3.1982758620689653,
 3.096774193548387,
 3.2721202003338896,
 3.0719530102790014,
 3.198966408268734,
 3.2081911262798637,
 3.136,
 3.158450704225352,
 3.1603408210689388,
 3.173824130879346,
 3.179856115107914,
 3.1936675461741424,
 3.116063138347261,
 3.111111111111111,
 3.156002875629044,
 3.1157495256166983,
 3.1182855552463122,
 3.

Lets visualise this numerical convergence. 

In [75]:
import matplotlib.pyplot as plt
plt.plot(log10_nsims, pi)
plt.axhline(y=np.pi, color='r', linestyle='-') # add red line 
plt.xlabel("$\log_{10}($nsims$)$") # add label with LaTex
plt.show() 

NameError: name 'log10_nsims' is not defined